#pragma once

enum OBJID { OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_END };

enum STATE { STATE_IDLE, STATE_RUN, STATE_JUMP };

enum STAGE { STAGE_START, STAGE_1, STAGE_2, STAGE_3, STAGE_END, STAGE_REPLAY};