#pragma once

enum OBJID { OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_END };

enum STATE { STATE_IDLE, STATE_RUN, STATE_JUMP };

enum DIRECTION { LEFT, RIGHT, END };

enum STAGE { STAGE_START, STAGE_EDIT, STAGE_1, STAGE_2, STAGE_3, STAGE_REPLAY, STAGE_END };